Issues/22 ndjson support
medizininformatik-initiative/mii-processes-common pull request #23
Opened 2024-10-27 22:15 UTC by wetret

resolves #22

2024-10-29 11:07 UTC, hhund requested changes
Behavior of `NdJsonDetector` `detect` method should be improved. See line by line comments.

2024-10-29 11:07 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/processes/common/mimetype/CombinedDetectors.java
> +
```suggestion
```

2024-10-30 09:35 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/processes/common/mimetype/NdJsonDetector.java
> +	public MediaType detect(InputStream inputStream, Metadata metadata) throws IOException
implemented in 836f5b8

2024-10-30 09:36 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/processes/common/mimetype/NdJsonDetector.java
> +	 */
implemented in 836f5b8

2024-10-30 09:38 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/processes/common/mimetype/CombinedDetectors.java
> +
implemented in 836f5b8

2024-11-04 14:42 UTC, merged