Asnyc request pattern, Binary stream support
medizininformatik-initiative/mii-processes-common pull request #30
Opened 2024-12-18 12:19 UTC by wetret

resolves #28 
resolves #29

2025-02-17 16:14 UTC, hhund requested changes
A change request and some suggestions.

2025-02-17 16:14 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/FhirClientFactory.java
> +			getBinaryStreamFhirClient().testConnection();
Assuming the code has no bugs a single connection test should be enough. I would suggest moving the testConnection method to the `StandardFhirClient` interface and removing the other implementation.

2025-02-17 16:14 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/AsyncFhirClientImpl.java
> +			HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
Do we want to use a String BodyHandler here? InputStream might be more efficient.

2025-02-17 16:14 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/BinaryStreamFhirClientImpl.java
> +				throw new RuntimeException("Reading Binary with id '" + unqualifiedId
Do we need to explicitly close the response InputStream if status is not 200, or will it be closed automatically? May block the client for future use if not closed.

2025-02-17 16:14 UTC, hhund commented on src/main/java/de/medizininformatik_initiative/processes/common/crypto/AesGcmUtil.java
> +			throw new IOException("Failed to read the complete encrypted AES key");
```suggestion
			throw new IOException("Failed to read the complete AES initialization vector");
```

2025-02-19 13:00 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/FhirClientFactory.java
> +			getBinaryStreamFhirClient().testConnection();
added variables to enable connection tests of special clients, implemented with 63d318a

2025-02-19 13:01 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/AsyncFhirClientImpl.java
> +			HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
using InputStream BodyHandler, implemented with 63d318a

2025-02-19 13:01 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/BinaryStreamFhirClientImpl.java
> +				throw new RuntimeException("Reading Binary with id '" + unqualifiedId
Implemented with 63d318a

2025-02-19 13:01 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/processes/common/crypto/AesGcmUtil.java
> +			throw new IOException("Failed to read the complete encrypted AES key");
fixed with 63d318a

2025-02-19 17:24 UTC, hhund approved these changes

2025-03-03 13:25 UTC, EmteZogaf commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/AsyncFhirClientImpl.java
> +		String locationPath = location.substring(location.indexOf("__async-status"));
The path prefix `__async-status` is blaze specific as the [documentation](http://hl7.org/fhir/R5/async-bundle.html#3.2.6.2.2.0.2) does not state a specific URI form.

2025-03-03 13:32 UTC, EmteZogaf commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/AsyncFhirClientImpl.java
> +		String locationPath = location.substring(location.indexOf("__async-status"));
Is it not equal to just keeping everything after the first `/`?

2025-03-03 15:19 UTC, wetret commented on src/main/java/de/medizininformatik_initiative/processes/common/fhir/client/AsyncFhirClientImpl.java
> +		String locationPath = location.substring(location.indexOf("__async-status"));
Using now the provided FHIR server baseURL to check wether the Content-Location starts with the same URL: 0ad23ab

2025-03-03 15:26 UTC, EmteZogaf approved these changes
lgtm

But we should add tests for the FhirClients code soon.

2025-03-21 14:31 UTC, merged